name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build-and-deploy:
    environment: staging
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
      - name: Register schema
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
        npx apollo service:push --graph=${{secrets.APOLLO_GRAPH_NAME}} --key=${{secrets.APOLLO_KEY}} --variant=${{secrets.APOLLO_GRAPH_VARIANT}}
